tag_0: {frame_id: tag_0, qw: 0.5, qx: 0.5, qy: -0.5, qz: -0.5, x: 2.92, y: 0.51, z: 0.52}
tag_15: {frame_id: tag_15, qw: 0.7, qx: 0.71, qy: -0.01, qz: -0.02, x: 4.15, y: 4.1,
  z: 0.52}
tag_5: {frame_id: tag_5, qw: 0.49, qx: -0.49, qy: 0.51, qz: -0.51, x: 7.77, y: -2.67,
  z: 0.52}
